
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pablo
 */
public class MetodosString extends javax.swing.JFrame {

    /**
     * Creates new form MetodosString
     */
    public MetodosString() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcadena = new javax.swing.JLabel();
        lblCadena1 = new javax.swing.JLabel();
        txtCadena1 = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblcadena.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblcadena.setForeground(new java.awt.Color(204, 51, 0));
        lblcadena.setText("CADENA");

        lblCadena1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCadena1.setForeground(new java.awt.Color(255, 0, 51));
        lblCadena1.setText("Ingrese la Cadena");

        txtCadena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadena1ActionPerformed(evt);
            }
        });

        btnValidar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(51, 0, 51));
        btnValidar.setText("VALIDAR");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCadena1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCadena1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblcadena)
                        .addGap(0, 226, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnValidar)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblcadena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadena1)
                    .addComponent(txtCadena1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnValidar)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadena1ActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        String oracion=txtCadena1.getText();
        this.VerificacionVocales(oracion);
    }//GEN-LAST:event_btnValidarActionPerformed
public void VerificacionVocales(String oracion){
    char [] oraciones=oracion.toCharArray();
    for(int i=0; i<oraciones.length ;i++){
        char letra = oraciones[i];
        if(letra=='a'){
            oraciones[i]='@';         
        }else if(letra=='e'){
            
        }else if(letra=='i'){
            
        }else if(letra=='o'){
            oraciones[i]='$'; 
        }else if(letra=='u'){
            
        }
    }
    
    String [] vocal = new String(oraciones).split(" ");
    
    int numeroletra=vocal.length;
    StringBuilder resultadoinvertido= new StringBuilder();
    for(int i = vocal.length-1;i>= 1 ;i--){
        resultadoinvertido.append(oracion);
        if(i>0){
            resultadoinvertido.append(" ");
        }
    }
    JOptionPane.showMessageDialog(this,"Oración modificada: " + new String(oraciones)+"\n"
    +"Número de palabras: " + numeroletra+"\n"+"Oración invertida: " + resultadoinvertido.toString());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodosString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodosString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodosString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodosString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodosString().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel lblCadena1;
    private javax.swing.JLabel lblcadena;
    private javax.swing.JTextField txtCadena1;
    // End of variables declaration//GEN-END:variables
}
